name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php: '8.1'
          extensions: sqlite, mbstring, xml, mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Configure .env
        run: cp .env.example .env
      - name: Generate APP Key
        run: php artisan key:generate --ansi


      - name: Run migrations
        run: php artisan migrate --env=testing --database=sqlite

      - name: Run tests
        run: php artisan test
